name: RandomizedRewardCommands
author: YitanTribal
description: randomize a list of commands with random chances.
main: cl.bismuthCode.RandomizedRewardCommands.Main;
version: 1
commands:
   RandomizedRewardCommands:
      usage: /<command>
      aliases: [rrc, rrcommands]